node {    
	git credentialsId: '45a5e0ca-2be8-4550-b0cd-3695a8498ea0', url: 'http://localhost:10080/n7down/Exile.git'

    echo 'update local.properties file'
    sh '''echo \'sdk.dir=/opt/sdk/adt-bundle-mac-x86_64-20130514/sdk\' > local.properties'''

    echo 'build'
    sh './gradlew core:clean'
    sh './gradlew desktop:clean'
    sh './gradlew desktop:dist'
    sh './gradlew desktop:buildPom'
    
    // echo 'publish to artifactory'
    sh './gradlew desktop:artifactoryPublish'
    
    echo 'generate javadoc'
    sh './gradlew core:javadoc'

    echo 'deploy javadocs'
    sh 'rm -rf /srv/docker/tomcat/webapps/exile-docs/*'
    sh 'cp -r core/build/docs/javadoc/* /srv/docker/tomcat/webapps/exile-docs/'
    
    echo 'run test cases'
    sh './gradlew core:test'
    
    echo 'deploy test report'
    sh 'rm -rf /srv/docker/tomcat/webapps/exile-tests/*'
    sh 'cp -r core/build/reports/tests/* /srv/docker/tomcat/webapps/exile-tests/'
    
    echo 'generate jacoco'
    sh './gradlew core:jacocoTestReport'
    
    echo 'deploy jacoco report'
    sh 'rm -rf /srv/docker/tomcat/webapps/exile-jacoco/*'
    sh 'cp -r core/build/reports/jacoco/html/* /srv/docker/tomcat/webapps/exile-jacoco/'
    sh 'cp -r core/build/reports/jacoco/html/.resources/ /srv/docker/tomcat/webapps/exile-jacoco/'
    sh 'cp -r core/build/reports/jacoco/html/.sessions.html /srv/docker/tomcat/webapps/exile-jacoco/'
    sh 'docker restart tomcat'
}
